---
# Add hosts to Ansible in-memory inventory
- name: Add host
  add_host:
    name: '{{ item.openstack.public_v4 }}'
    groups: instances
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

# save using template
- name: save inventory
  become: yes
  template:
    src: hosts.j2
    dest: '{{inventory_file}}'