# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: vol-instance1
    vol_size: 10
  - vol_name: vol-instance2
    vol_size: 10


# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: instance1
    volumes: ['vol-instance1']
  - name: instance2
    volumes: ['vol-instance2']

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: demo
instance_flavor: uom.mse.1c4g

# inventory file save path
inventory_file: "./inventory/inventory_file.ini"

#ansible
ansiple_python_interpreter: /usr/bin/python3
ansible_user: ubuntu
ansible_ssh_private_key_file: demo.pem


#couchDB
couchdb_user: admin
couchdb_password: admin
couchdb_image_version: ibmcom/couchdb3:3.1.1
couchdb_cookie: brumbrum


# twitter harvester docker image config
harvester_name: "twitter_stream_harvest" 
harvester_image: "hh1752756228/twitter_stream_harvest:v1"
harvester_dockerhub_username: hh1752756228
harvester_dockerhub_password: zz77971010