# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: vol-instance3
    vol_size: 10


# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: instance3-webserver
    volumes: ['vol-instance3']

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: demo
instance_flavor: uom.mse.2c9g

# inventory file save path
inventory_file: "./inventory/inventory_webserver_file.ini"

#ansible
ansiple_python_interpreter: /usr/bin/python3
ansible_user: ubuntu
ansible_ssh_private_key_file: demo.pem

# backend docker image config
backend_process: flask_app
backend_image: motianyi/ccc-flask-backend:v2
backend_port: 8887
backend_dockerhub_username: motianyi
backend_dockerhub_password: makesense