- name: Log into DockerHub
  become: yes
  docker_login:
    username: "{{ backend_dockerhub_username }}"
    password: "{{ backend_dockerhub_password }}"

- name: pull image
  become: yes
  shell: docker pull "{{ backend_image }}"

- name: stop server
  become: yes
  shell: docker rm -f "{{ backend_process }}"

# Start the web server
- name: start server
  become: yes
  shell: docker run --name "{{ backend_process }}" -p "{{ backend_port }}":8003 -d "{{ backend_image }}"

- name: Log out from DockerHub
  become: yes
  docker_login:
    state: absent