- name: Log into DockerHub
  become: yes
  docker_login:
    username: "{{ backend_dockerhub_username }}"
    password: "{{ backend_dockerhub_password }}"

- name: pull image
  become: yes
  shell: docker pull "{{ backend_image }}"

- name: stop server named flask_app
  become: yes
  shell: docker rm -f flask_app

# Start the web server
- name: start server
  become: yes
  shell: docker run --name flask_app -p "{{ backend_port }}":8003 -d "{{ backend_image }}"

- name: Log out from DockerHub
  become: yes
  docker_login:
    state: absent