---
# UniMelb Research Cloud can have sporadic issues and assign you non-public IP addresses. 
# The following proxy settings should be used to allow your instances to be accessible 
# externally and hence allow updates to happen etc. Append this into /etc/environment on 
# any instances that you create that need external access to the Internet.

- name: set up proxy in /etc/environment
  become: yes
  blockinfile:
    path: /etc/environment
    block: |
      HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/
      HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/
      http_proxy=http://wwwproxy.unimelb.edu.au:8000/
      https_proxy=http://wwwproxy.unimelb.edu.au:8000/
      no_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au


          