---

- name: Gather facts of remote host
  setup:
    gather_subset: all

# Install dependencies on the host
- name: Install pip
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"


- name: install dependency packages, git, vim and docker
  tags: always
  become: yes
  
  apt:
    name: ['git','vim','python3-dev','python3-setuptools','python3-docker','docker.io','docker-compose']
    state: latest
    install_recommends: no
    update_cache: yes