- hosts: instances
  vars:
    ansible_python_interpreter:  /usr/bin/python3
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    # - role: openstack-common
    # - role: deploy-couchDB

- hosts: 172.26.128.223
  vars_files:
    - host_vars/mrc.yaml
  roles:
    - role: deploy-couchDB-cluster