- hosts: localhost
  vars:
    ansible_python_interpreter: /Users/motianyi/miniconda3/envs/ccc3.8/bin/python
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    # - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance
    