- hosts: instances
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: set-up-http-proxy
    - role: dependency
    - role: set-up-docker-http-proxy

- hosts: instances
  vars:
    ansible_python_interpreter:  /usr/bin/python3
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true
  roles:
    - role: deploy-couchDB

- hosts: localhost
  vars_files:
    - host_vars/mrc.yaml
  roles:
    - role: deploy-couchDB-cluster
    - role: deploy-couchDB-grunt