- hosts: instances
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - $vars_files
  gather_facts: true

  roles:
    - role: set-up-http-proxy
    - role: dependency
    - role: set-up-docker-http-proxy
